# machine properties
machine: ''
host: ''
host_opts: {}
queue_opts: []
ppn_range: []
maxnodes: 1
maxcores: 0
maxram: 0
maxtime: 1440
python: python
f2py_flags: ''

# job parameters
argv: []
name: job
verbose: 1
account: ''
email: ''
queue: ''
nproc: 1
nthread: -1
nstripe: -2
minutes: 0
pmem: 0
mode: ''
mode_opts: {}
executable: ''
execute: mpiexec -np {nproc} {executable}
notify_threshold: 4096
depend: ''
depend_flag: ''
notify_flag: ''
submit_flags: ''
binary_flag: ''
script_flag: ''
submit: ''
submit_pattern: (?P<jobid>\d+\S*)\D*$
wrapper: ''
