# job parameters
name: job
verbose: 1
account: ''
email: ''
run: ''
queue: ''
depend: ''
command: ''
pre: ''
post: ''
nproc: 1
nthread: 0
nstripe: -2
minutes: 0
pmem: 0
iodir: ''
argv: []

# machine properties
machine: ''
host: ''
host_opts: {}
queue_opts: []
ppn_range: []
maxnodes: 1
maxcores: 0
maxram: 0
maxtime: 0
rate: 1000000
python: python
f2py_flags: ''

# job scheduler
notify_threshold: 4096
notify: -m abe
launch: mpiexec -np {nproc} {command}
submit: qsub {notify} {submit_flags} "{name}.sh"
submit2: qsub {notify} -W depend="afterok:{depend}" {submit_flags} "{name}.sh"
submit_flags: ''
submit_pattern: (?P<jobid>\d+\S*)\D*$

# job script
script: |
    #!/bin/sh
    cd "${rundir}"
    env >> "{name}.env"
    echo "$( date ): {name} started" >> "{name}.out"
    {pre} >> "{name}.out"
    {launch} >> "{name}.out"
    {post} >> "{name}.out"
    echo "$( date ): {name} finished" >> "{name}.out"
