# CST job parameters
name: job
verbose: 1
account: ''
email: ''
run: 'exec'
queue: ''
depend: ''
command: ''
pre: ''
post: ''
nproc: 1
nthread: 0
nstripe: -2
minutes: 0
pmem: 0
path: 'run'
iopath: ''
argv: []

# machine properties
machine: ''
host: ''
host_opts: {}
queue_opts: []
ppn_range: []
maxnodes: 1
maxcores: 0
maxram: 0
maxtime: 0
rate: 1000000
python: python
f2py_flags: ''

# job scheduler
launch: mpiexec -np {nproc} {command}
notify_flag: -m abe
notify_threshold: 4096
depend_flag: -W depend="afterok:{depend}"
submit_flags: ''
submit: qsub {notify_flag} {depend_flag} {submit_flags} "{name}.sh"
submit_pattern: (?P<jobid>\d+\S*)\D*$

# job script
script: |
    #!/bin/sh
    cd "${path}"
    env > "{name}.env"
    date
    {pre}
    {launch}
    {post}
    date
