# I/O and code execution parameters
nproc3: [1, 1, 1]        # number of processors in [j, k, l]
mpin: 1                  # input:  0=separate files, 1=MPI-IO, -1=non-collective MPI-IO
mpout: 1                 # output: 0=separate files, 1=MPI-IO, -1=non-collective MPI-IO
itstats: 10              # interval fr calculating statistics
itio: 50                 # interval for writing i/o buffers
itbuff: 10               # buffer size for time series output
debug: 0                 # >1 sync, >2 mpi vars, >3 I/O

# Spatial difference operator
diffop: 'auto'           # cons, rect, para, quad, exac, save, auto

# Mesh parameters
shape: [41, 41, 41, 41]  # mesh size [nx, ny, nz, nt]
delta:                   # step length [dx, dy, dz, dt]
    [100.0, 100.0, 100.0, 0.0075]
affine:                  # grid transformation
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [0.0, 0.0, 1.0]
rexpand: 1.06            # grid expansion ratio
n1expand: [0, 0, 0]      # number of grid expansion nodes - near side
n2expand: [0, 0, 0]      # number of grid expansion nodes - far side
gridnoise: 0.0           # random noise added to mesh, assumes planar fault
tm0: 0.0                 # initial time

# Material model
rho: 2670.0              # density
vp:  6000.0              # P-wave speed
vs:  3464.0              # S-wave speed
gam: 0.0                 # viscosity
rho_min: -1.0            # min density
rho_max: -1.0            # max density
vp_min:  -1.0            # min P-wave speed
vp_max:  -1.0            # max P-wave speed
vs_min:  -1.0            # min S-wave speed
vs_max:  -1.0            # max S-wave speed
gam_min: -1.0            # min viscosity
gam_max: 0.8             # max viscosity
hourglass: [1.0, 1.0]    # hourglass stiffness (1) and viscosity (2)
vdamp: -1.0              # Vs dependent damping

# Boundary conditions
bc1: [free, free, free]  # near x, y, z surface
bc2: [free, free, free]  # far x, y, z surface
npml: 10                 # number of PML damping nodes
ppml: 2                  # PML exponent, 1-4. Generally 2 is best.
vpml: -1.0               # damping velocity, <0 default to min, max V_s harmonic mean

# Finite source parameters
nsource: 0               # number of sub-faults
source: potency          # potency, moment, force, or none

# Dynamic rupture parameters
ihypo: [1.0, 1.0, 1.0]   # hypocenter indices for nucleation
slipvector:              # shear traction direction for ts1
     [1.0, 0.0, 0.0]
faultnormal: 0           # normal direction to fault plane (0=no fault)
faultopening: 0          # 0=not allowed, 1=allowed
vrup: -1.0               # nucleation rupture velocity, negative = no nucleation
rcrit: 1000.0            # nucleation critical radius
trelax: 0.075            # nucleation relaxation time
svtol: 0.001             # slip velocity considered rupturing

